"""add Telegram chat history

Revision ID: 84e897b2279a
Revises: a8c5e1d2f904
Create Date: 2026-09-12 18:59:34.295757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84e897b2279a'
down_revision: Union[str, None] = 'a8c5e1d2f904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['core_channel_contacts.id'], name='fk_core_chat_messages_contact_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'message_id', name='uq_core_chat_messages_contact_message')
    )
    with op.batch_alter_table('core_chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_core_chat_messages_contact_created_message', ['contact_id', 'created_at', 'message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_chat_messages_contact_id'), ['contact_id'], unique=False)

    with op.batch_alter_table('core_channel_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_messages', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('save_messages_enabled_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_channel_contacts', schema=None) as batch_op:
        batch_op.drop_column('save_messages_enabled_at')
        batch_op.drop_column('save_messages')

    with op.batch_alter_table('core_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_chat_messages_contact_id'))
        batch_op.drop_index('ix_core_chat_messages_contact_created_message')

    op.drop_table('core_chat_messages')
    # ### end Alembic commands ###
